using Avalonia.Media;
using Nikse.SubtitleEdit.Features.Assa;
using System;

namespace Nikse.SubtitleEdit.Logic.Config;

public class SeVideo
{
    public SeVideoBurnIn BurnIn { get; set; }
    public SeVideoTransparent Transparent { get; set; }
    public SeVideoTextToSpeech TextToSpeech { get; set; }
    public SeVideoOcr VideoOcr { get; set; }
    public string VideoPlayer { get; set; }
    public double Volume { get; set; }
    public bool ShowStopButton { get; set; }
    public bool ShowFullscreenButton { get; set; }
    public bool FullscreenHideControls { get; set; }
    public bool AutoOpen { get; set; }
    public bool OpenSearchParentFolder { get; set; }
    public string CutType { get; set; }
    public string ShowChangesFFmpegArguments { get; set; }
    public bool VideoPlayerDisplayTimeLeft { get; set; }
    public string CutDefaultVideoExtension { get; set; }
    public bool CutAlsoCutSubtitle { get; set; }
    public bool OpenFromUrlDownloadVideo { get; set; } = true;
    public bool OpenFromUrlDownloadSubtitles { get; set; }
    public bool OpenFromUrlIncludeAutoGeneratedSubtitles { get; set; }
    public int MoveVideoPositionCustom1Back { get; set; }
    public int MoveVideoPositionCustom1Forward { get; set; }
    public int MoveVideoPositionCustom2Back { get; set; }
    public int MoveVideoPositionCustom2Forward { get; set; }
    public int MoveVideoPositionCustom3Back { get; set; }
    public int MoveVideoPositionCustom3Forward { get; set; }
    public int MoveVideoPositionCustom4Back { get; set; }
    public int MoveVideoPositionCustom4Forward { get; set; }

    public string MpvPreviewFontName { get; set; }
    public int MpvPreviewFontSize { get; set; }
    public bool MpvPreviewFontBold { get; set; }
    public int MpvPreviewMargin { get; set; }
    public string MpvPreviewColorPrimary { get; set; }
    public string MpvPreviewColorOutline { get; set; }
    public string MpvPreviewColorShadow { get; set; }
    public decimal MpvPreviewOutlineWidth { get; set; }
    public string MpvPreviewAlignment { get; set; }
    public decimal MpvPreviewShadowWidth { get; set; }
    public int MpvPreviewBorderType { get; set; }

    /// <summary>
    /// Show the lines where the subtitle file says they belong (TTML regions, PAC vertical
    /// alignment, EBU STL teletext rows) instead of at <see cref="MpvPreviewAlignment"/>.
    /// </summary>
    public bool MpvPreviewUsePositionFromFile { get; set; }

    /// <summary>
    /// mpv's "audio-buffer" option in seconds, applied when a player core is created. mpv's
    /// own default is 0.2 s, and that buffer is why pause/resume/seek take effect ~200 ms
    /// late - the residual the waveform playhead code has to mask. Kept small here; raise it
    /// (or set 0 to use mpv's default) if audio stutters on slow hardware or Bluetooth audio.
    /// </summary>
    public double MpvAudioBufferSeconds { get; set; }

    public SeVideo()
    {
        BurnIn = new();
        Transparent = new();
        TextToSpeech = new();
        VideoOcr = new();
        VideoPlayer = OperatingSystem.IsWindows() ? VideoPlayerName.MpvWid : VideoPlayerName.MpvOpenGl;
        Volume = 60;
        ShowStopButton = true;
        ShowFullscreenButton = true;
        AutoOpen = true;
        OpenSearchParentFolder = true;
        CutType = Features.Video.CutVideo.CutType.MergeSegments.ToString();
        CutDefaultVideoExtension = ".mkv";
        // No "-vsync vfr": ffmpeg 9 removed the long-deprecated -vsync option and aborts with
        // "Unrecognized option 'vsync'", so shot change detection found nothing. It never did
        // anything here anyway - the output is discarded by "-f null -".
        ShowChangesFFmpegArguments = "-i \"{0}\" -vf \"select=gt(scene\\,{1}),showinfo\" -threads 0 -f null -";
        MoveVideoPositionCustom1Back = 2000; // 2 seconds
        MoveVideoPositionCustom1Forward = 2000; // 2 seconds
        MoveVideoPositionCustom2Back = 5000; // 5 seconds
        MoveVideoPositionCustom2Forward = 5000; // 5 seconds
        MoveVideoPositionCustom3Back = 10000; // 10 seconds
        MoveVideoPositionCustom3Forward = 10000; // 10 seconds
        MoveVideoPositionCustom4Back = 30000; // 30 seconds
        MoveVideoPositionCustom4Forward = 30000; // 30 seconds

        MpvPreviewFontName = "Arial";
        MpvPreviewFontSize = 20;
        MpvPreviewFontBold = true;
        MpvPreviewMargin = 10;
        MpvPreviewOutlineWidth = 2;
        MpvPreviewAlignment = "2"; // Bottom-center
        MpvPreviewShadowWidth = 1;
        MpvPreviewColorPrimary = Color.FromRgb(255, 255, 255).FromColorToHex();
        MpvPreviewColorOutline = Color.FromRgb(0, 0, 0).FromColorToHex();
        MpvPreviewColorShadow = Color.FromRgb(0, 0, 0).FromColorToHex();
        MpvPreviewBorderType = (int)BorderStyleType.Outline;
        MpvPreviewUsePositionFromFile = true;
        MpvAudioBufferSeconds = 0.05;
    }
}