using System;

namespace Nikse.SubtitleEdit.Logic.Config.Language.Tools;

public class LanguageVideo
{
    public LanguageBurnIn BurnIn { get; set; } = new();
    public LanguageTransparentVideo VideoTransparent { get; set; } = new();
    public LanguageAudioToText AudioToText { get; set; } = new();
    public LanguageTextToSpeech TextToSpeech { get; set; } = new();
    public LanguageShotChanges ShotChanges { get; set; } = new();
    public LanguageVideoOcr VideoOcr { get; set; } = new();
    public string GoToVideoPosition { get; set; }
    public string GoToVideoPositionDotDotDot { get; set; }
    public string GenerateBlankVideoDotDotDot { get; set; }
    public string GenerateBlankVideoTitle { get; set; }
    public string ReEncodeVideoForBetterSubtitlingTitle { get; set; }
    public string ReEncodeVideoForBetterSubtitlingDotDotDot { get; set; }
    public string OpenSecondarySubtitleOnVideoPlayerDotDotDot { get; set; }
    public string OpenSecondarySubtitleOnVideoPlayer { get; set; }
    public string RemoveSecondarySubtitleOnVideoPlayer { get; set; }
    public string CutVideoTitle { get; set; }
    public string CutVideoDotDotDot { get; set; }
    public string EmbedSubtitlesDotDotDot { get; set; }
    public string GenerateTimeCodes { get; set; }
    public string CheckeredImage { get; set; }
    public string PromptForFfmpegParamsAndGenerate { get; set; }
    public string CutVideoCutSegments { get; set; }
    public string CutVideoMergeSegments { get; set; }
    public string CutVideoSplitSegments { get; set; }
    public string CutVideoAlsoCutSubtitle { get; set; }
    public string CutVideoSubtitleFileGeneratedX { get; set; }
    public string ImportCurrentSubtitle { get; set; }
    public string AddRemoveEmbeddedSubtitlesTitle { get; set; }
    public string AddRemoveEmbeddedSubtitlesMp4Title { get; set; }
    public string AddCurrentSubtitle { get; set; }
    public string EmbeddedTrackNoSubtitlesFoundTitle { get; set; }
    public string EmbeddedTrackNoSubtitlesFoundMessage { get; set; }
    public string EmbeddedTrackNoTracksTitle { get; set; }
    public string EmbeddedTrackNoTracksMessage { get; set; }
    public string EmbeddedTrackUnableToGenerateTitle { get; set; }
    public string EmbeddedTrackUnableToGenerateMessage { get; set; }
    public string EmbeddedTrackPreviewUnavailableTitle { get; set; }
    public string EmbeddedTrackPreviewUnavailableMessage { get; set; }
    public string EmbeddedTrackGeneratingVideoXY { get; set; }
    public string EmbeddedTrackGeneratingVideo { get; set; }
    public string Mp4FilesFilter { get; set; }
    public string ViewMatroskaTrackX { get; set; }
    public string ResolutionSeparator { get; set; }
    public string OpenFromUrlTitle { get; set; }
    public string OpenFromUrlOpenOnline { get; set; }
    public string OpenFromUrlOpenOnlineDescription { get; set; }
    public string OpenFromUrlOpenOnlineNote { get; set; }
    public string OpenFromUrlDownloadAndOpen { get; set; }
    public string OpenFromUrlDownloadAndOpenDescription { get; set; }
    public string OpenFromUrlDownloadAndOpenNote { get; set; }
    public string OpenFromUrlDownloadingTitle { get; set; }
    public string OpenFromUrlDownloadSubtitles { get; set; }
    public string OpenFromUrlDownloadVideo { get; set; }
    public string OpenFromUrlIncludeAutoGeneratedSubtitles { get; set; }
    public string AssaStyleWillBeUsed { get; set; }
    public string PickOnlineSubtitleTitle { get; set; }
    public string OutputSettingsTitle { get; set; }
    public string TtsCrispAsrSettingsTitle { get; set; }
    public string TtsDownloadEngineTitle { get; set; }
    public string PickOnlineSubtitleFetching { get; set; }
    public string PickOnlineSubtitleNoneFound { get; set; }
    public string ForcedAligner { get; set; }
    public string PostProcessing { get; set; }
    public string ToggleCurrentSubtitleWhilePlaying { get; set; }
    public string ToggleSubtitlesOnVideoPlayer { get; set; }
    public string SubtitlesOnVideoPlayerOn { get; set; }
    public string SubtitlesOnVideoPlayerOff { get; set; }
    public string OnlyMkvCanSupportEmbeddedSubtitleEditing { get; set; }
    public string ReEncodeInfo { get; set; }
    public string ReEncodeGeneratingVideoX { get; set; }
    public string ReEncodeGeneratingVideoXofY { get; set; }
    public string ReEncodeUnableToGenerateVideo { get; set; }
    public string ReEncodeOutputVideoFileNotGenerated { get; set; }
    public string ReEncodeGeneratingDone { get; set; }
    public string ReEncodeGeneratedFilesX { get; set; }
    public string ReEncodeFfmpegParameters { get; set; }
    public string Voices { get; set; }
    public string Presets { get; set; }
    public string TalkerX { get; set; }
    public string BaseModel { get; set; }
    public string TurboModel { get; set; }
    public string TtsUpdateX { get; set; }
    public string TtsEngineNotInstalled { get; set; }
    public string TtsEngineUpdateAvailable { get; set; }
    public string TtsEngineTooOldUpdateRequired { get; set; }
    public string TtsEngineChatterboxCapable { get; set; }

    public LanguageVideo()
    {
        GoToVideoPosition = "Go to video position";
        GoToVideoPositionDotDotDot = "Go to video position...";
        GenerateBlankVideoTitle = "Generate blank video";
        GenerateBlankVideoDotDotDot = "Generate blank video...";
        ReEncodeVideoForBetterSubtitlingTitle = "Re-encode video for better subtitling";
        ReEncodeVideoForBetterSubtitlingDotDotDot = "Re-encode video for better subtitling...";
        OpenSecondarySubtitleOnVideoPlayer = "Secondary subtitle (on video player)";
        OpenSecondarySubtitleOnVideoPlayerDotDotDot = "Secondary subtitle on video player, open...";
        RemoveSecondarySubtitleOnVideoPlayer = "Secondary subtitle on video player, remove";
        CutVideoTitle = "Cut video";
        CutVideoDotDotDot = "Cut video...";
        EmbedSubtitlesDotDotDot = "Add/remove embedded subtitles...";
        GenerateTimeCodes = "Generate time codes";
        CheckeredImage = "Checkered image";
        PromptForFfmpegParamsAndGenerate = "Prompt for ffmpeg parameters and generate";
        CutVideoCutSegments = "Cut segments";
        CutVideoMergeSegments = "Merge segments";
        CutVideoSplitSegments = "Save segments individually";
        CutVideoAlsoCutSubtitle = "Also cut subtitle";
        CutVideoSubtitleFileGeneratedX = "Subtitle file generated: {0}";
        ImportCurrentSubtitle = "Import current subtitle";
        AddRemoveEmbeddedSubtitlesTitle = "Add/remove embedded subtitles";
        AddRemoveEmbeddedSubtitlesMp4Title = "Add/remove embedded subtitles (MP4)";
        AddCurrentSubtitle = "Add current subtitle";
        EmbeddedTrackNoSubtitlesFoundTitle = "No subtitles found";
        EmbeddedTrackNoSubtitlesFoundMessage = "The selected subtitle file does not contain any subtitles.";
        EmbeddedTrackNoTracksTitle = "No tracks added";
        EmbeddedTrackNoTracksMessage = "Add one or more subtitle tracks, or load a video that already has embedded subtitles.";
        EmbeddedTrackUnableToGenerateTitle = "Unable to generate video";
        EmbeddedTrackUnableToGenerateMessage = "Output video file not generated: {0}{1}Parameters: {2}";
        EmbeddedTrackPreviewUnavailableTitle = "Preview not available";
        EmbeddedTrackPreviewUnavailableMessage = "Could not extract the selected subtitle stream. The codec may not be a text format that ffmpeg can convert to SRT (e.g. bitmap-based subtitles).";
        EmbeddedTrackGeneratingVideoXY = "Generating video... {0}%     {1}";
        EmbeddedTrackGeneratingVideo = "Generating video...";
        Mp4FilesFilter = "MP4 files";
        ViewMatroskaTrackX = "View Matroska track - {0}";
        ResolutionSeparator = "x";
        OpenFromUrlTitle = "Open video file from URL";
        OpenFromUrlOpenOnline = "Open online";
        OpenFromUrlOpenOnlineDescription = "Stream the video directly. Fastest start.";
        OpenFromUrlOpenOnlineNote = "Speech-to-text and waveform spikes are not available in this mode.";
        OpenFromUrlDownloadAndOpen = "Download and open";
        OpenFromUrlDownloadAndOpenDescription = "Save the video locally, then open it.";
        OpenFromUrlDownloadAndOpenNote = "Required for speech-to-text and waveform spikes.";
        OpenFromUrlDownloadingTitle = "Downloading video";
        OpenFromUrlDownloadSubtitles = "Download subtitles";
        OpenFromUrlDownloadVideo = "Download video";
        OpenFromUrlIncludeAutoGeneratedSubtitles = "Include auto-generated subtitles (original language)";
        PickOnlineSubtitleTitle = "Pick subtitle to download";
        PickOnlineSubtitleFetching = "Downloading subtitles...";
        PickOnlineSubtitleNoneFound = "No subtitles found for this URL.";
        ForcedAligner = "Forced aligner";
        PostProcessing = "Post-processing...";
        ToggleCurrentSubtitleWhilePlaying = "Toggle current subtitle while playing";
        ToggleSubtitlesOnVideoPlayer = "Toggle subtitles on video player";
        SubtitlesOnVideoPlayerOn = "Subtitles on video player: on";
        SubtitlesOnVideoPlayerOff = "Subtitles on video player: off";
        OnlyMkvCanSupportEmbeddedSubtitleEditing = "Only Matroska (.mkv, .webm) files are supported for editing embedded subtitles.";
        ReEncodeInfo = "Re-encoding can make subtitling smoother:" + Environment.NewLine +
                       "• Smaller resolution (high resolutions make subtitling slow)" + Environment.NewLine +
                       "• Re-encode the video to H.264 + yuv420p makes it more compatible" + Environment.NewLine +
                       "• Optimized for fast seeking";
        ReEncodeGeneratingVideoX = "Generating video... {0}%     {1}";
        ReEncodeGeneratingVideoXofY = "Generating video {0}/{1}... {2}%     {3}";
        ReEncodeUnableToGenerateVideo = "Unable to generate video";
        ReEncodeOutputVideoFileNotGenerated = "Output video file not generated: {0}" + Environment.NewLine + "Parameters: {1}";
        ReEncodeGeneratingDone = "Generating done";
        ReEncodeGeneratedFilesX = "Generated files ({0}):";
        ReEncodeFfmpegParameters = "ffmpeg parameters";
        AssaStyleWillBeUsed = "Current ASSA style will be used" + Environment.NewLine + Environment.NewLine +
                              "Change subtitle format if" + Environment.NewLine +
                              "you want to set styles here";
        Voices = "Voices";
        Presets = "Presets";
        TalkerX = "Talker {0}";
        BaseModel = "Base model";
        TurboModel = "Turbo model";
        TtsUpdateX = "Update {0}";
        TtsEngineNotInstalled = "{0} not installed";
        TtsEngineUpdateAvailable = "{0} - update available";
        TtsEngineTooOldUpdateRequired = "{0} too old - update required";
        TtsEngineChatterboxCapable = "{0} (Chatterbox-capable)";
        OutputSettingsTitle = "Output settings";
        TtsCrispAsrSettingsTitle = "{0} (CrispASR) settings";
        TtsDownloadEngineTitle = "TTS - Download engine";
    }
}