using Nikse.SubtitleEdit.Core.Common;
using Nikse.SubtitleEdit.UiLogic.Translate;
using System;
using System.Collections.Generic;

namespace Nikse.SubtitleEdit.UiLogic.AutoTranslate
{
    /// <summary>
    /// The 419 languages the MADLAD-400 model can translate into.
    ///
    /// MADLAD picks the target language from a control token prepended to the source text
    /// (<c>&lt;2de&gt;</c> for German), so only codes that exist as such a token in the model
    /// vocabulary work. A code that does not - "yue", or a typo - is not rejected anywhere: the
    /// tokenizer splits it into ordinary pieces and the model quietly translates into whatever
    /// language that steers it towards (Spanish, in practice), with no warning and a zero exit
    /// code. This list therefore comes from the vocabulary of <c>madlad400-3b-mt</c> and not from
    /// .NET's culture list, which used to fill the combo and offered 107 languages the model has
    /// no token for (Cantonese, Norwegian Bokmal, Asturian, Kabyle, Konkani...) while hiding 231
    /// it does know.
    ///
    /// The vocabulary also holds tags with a script or region suffix (<c>&lt;2zh_Hant&gt;</c>,
    /// <c>&lt;2nan_Latn_TW&gt;</c>) and a few non-language ones (<c>&lt;2translate&gt;</c>,
    /// <c>&lt;2back_translated&gt;</c>). Those are left out deliberately - passing them on the
    /// CrispASR command line lands in the same wrong-language fallback as an unknown code, so
    /// Traditional Chinese is not reachable through this engine.
    ///
    /// Names are .NET's <c>CultureInfo.EnglishName</c> where the code is a known culture, and the
    /// ISO 639-3 reference name otherwise.
    /// </summary>
    public static class CrispAsrMadladLanguages
    {
        private static readonly HashSet<string> Codes = new HashSet<string>(List().ConvertAll(p => p.Code), StringComparer.Ordinal);

        /// <summary>
        /// The target languages, ordered by English name.
        /// </summary>
        public static List<TranslationPair> List()
        {
            return new List<TranslationPair>
            {
                MakePair("Achinese", "ace"),
                MakePair("Adangme", "ada"),
                MakePair("Adhola", "adh"),
                MakePair("Adyghe", "ady"),
                MakePair("Afrikaans", "af"),
                MakePair("Aguaruna", "agr"),
                MakePair("Agusan Manobo", "msm"),
                MakePair("Akan", "ak"),
                MakePair("Akha", "ahk"),
                MakePair("Albanian", "sq"),
                MakePair("Alur", "alz"),
                MakePair("Amazigh", "ber"),
                MakePair("Ambulas", "abt"),
                MakePair("Amharic", "am"),
                MakePair("Ancient Greek", "grc"),
                MakePair("Arabic", "ar"),
                MakePair("Aragonese", "an"),
                MakePair("Armenian", "hy"),
                MakePair("Arpitan", "frp"),
                MakePair("Assamese", "as"),
                MakePair("Assyrian", "syr"),
                MakePair("Avaric", "av"),
                MakePair("Awa-Cuaiquer", "kwi"),
                MakePair("Awadhi", "awa"),
                MakePair("Ayacucho Quechua", "quy"),
                MakePair("Aymara", "ay"),
                MakePair("Azerbaijani", "az"),
                MakePair("Balinese", "ban"),
                MakePair("Bambara", "bm"),
                MakePair("Bangla", "bn"),
                MakePair("Banjar", "bjn"),
                MakePair("Baoulé", "bci"),
                MakePair("Basaa", "bas"),
                MakePair("Bashkir", "ba"),
                MakePair("Basque", "eu"),
                MakePair("Batak Angkola", "akb"),
                MakePair("Batak Karo", "btx"),
                MakePair("Batak Simalungun", "bts"),
                MakePair("Batak Toba", "bbc"),
                MakePair("Bavarian", "bar"),
                MakePair("Belarusian", "be"),
                MakePair("Belize Kriol English", "bzj"),
                MakePair("Betawi", "bew"),
                MakePair("Bhojpuri", "bho"),
                MakePair("Bikol", "bik"),
                MakePair("Bimoba", "bim"),
                MakePair("Bislama", "bi"),
                MakePair("Bodo", "brx"),
                MakePair("Boko", "bqc"),
                MakePair("Bokobaru", "bus"),
                MakePair("Bosnian", "bs"),
                MakePair("Breton", "br"),
                MakePair("Buginese", "bug"),
                MakePair("Bukiyip", "ape"),
                MakePair("Bulgarian", "bg"),
                MakePair("Bulu", "bum"),
                MakePair("Buriat", "bua"),
                MakePair("Burmese", "my"),
                MakePair("Cajamarca Quechua", "qvc"),
                MakePair("Caribbean Javanese", "jvn"),
                MakePair("Carpathian Romani", "rmc"),
                MakePair("Catalan", "ca"),
                MakePair("Cañar Highland Quichua", "qxr"),
                MakePair("Cebuano", "ceb"),
                MakePair("Central Atlas Tamazight", "tzm"),
                MakePair("Central Mazahua", "maz"),
                MakePair("Chamorro", "ch"),
                MakePair("Chavacano", "cbk"),
                MakePair("Chechen", "ce"),
                MakePair("Cherokee", "chr"),
                MakePair("Chhattisgarhi", "hne"),
                MakePair("Chinese", "zh"),
                MakePair("Chol", "ctu"),
                MakePair("Chopi", "cce"),
                MakePair("Chuj", "cac"),
                MakePair("Chuukese", "chk"),
                MakePair("Chuvash", "cv"),
                MakePair("Cornish", "kw"),
                MakePair("Corsican", "co"),
                MakePair("Crimean Tatar", "crh"),
                MakePair("Croatian", "hr"),
                MakePair("Czech", "cs"),
                MakePair("Dadibi", "mps"),
                MakePair("Danish", "da"),
                MakePair("Dari", "prs"),
                MakePair("Darlong", "dln"),
                MakePair("Dawro", "dwr"),
                MakePair("Dhivehi", "dv"),
                MakePair("Dinka", "din"),
                MakePair("Ditammari", "tbz"),
                MakePair("Dogri", "doi"),
                MakePair("Dombe", "dov"),
                MakePair("Dutch", "nl"),
                MakePair("Dyula", "dyu"),
                MakePair("Dzongkha", "dz"),
                MakePair("Eastern Balochi", "bgp"),
                MakePair("Eastern Bolivian Guaraní", "gui"),
                MakePair("Eastern Bru", "bru"),
                MakePair("Eastern Huasteca Nahuatl", "nhe"),
                MakePair("Eastern Maroon Creole", "djk"),
                MakePair("Eastern Tamang", "taj"),
                MakePair("Egyptian Arabic", "arz"),
                MakePair("Enga", "enq"),
                MakePair("English", "en"),
                MakePair("Epena", "sja"),
                MakePair("Erzya", "myv"),
                MakePair("Esperanto", "eo"),
                MakePair("Estonian", "et"),
                MakePair("Ewe", "ee"),
                MakePair("Falam Chin", "cfm"),
                MakePair("Faroese", "fo"),
                MakePair("Fiji Hindi", "hif"),
                MakePair("Fijian", "fj"),
                MakePair("Filipino", "fil"),
                MakePair("Finnish", "fi"),
                MakePair("Fipa", "fip"),
                MakePair("Fon", "fon"),
                MakePair("French", "fr"),
                MakePair("Friulian", "fur"),
                MakePair("Fula", "ff"),
                MakePair("Gagauz", "gag"),
                MakePair("Galician", "gl"),
                MakePair("Ganda", "lg"),
                MakePair("Garhwali", "gbm"),
                MakePair("Garifuna", "cab"),
                MakePair("Georgian", "ka"),
                MakePair("German", "de"),
                MakePair("Goan Konkani", "gom"),
                MakePair("Gofa", "gof"),
                MakePair("Gorontalo", "gor"),
                MakePair("Greek", "el"),
                MakePair("Guahibo", "guh"),
                MakePair("Guajajára", "gub"),
                MakePair("Guarani", "gn"),
                MakePair("Guerrero Amuzgo", "amu"),
                MakePair("Guerrero Nahuatl", "ngu"),
                MakePair("Gujarati", "gu"),
                MakePair("Gulay", "gvl"),
                MakePair("Haitian Creole", "ht"),
                MakePair("Hakha Chin", "cnh"),
                MakePair("Hausa", "ha"),
                MakePair("Hawaiian", "haw"),
                MakePair("Hebrew", "he"),
                MakePair("Hiligaynon", "hil"),
                MakePair("Hindi", "hi"),
                MakePair("Hiri Motu", "ho"),
                MakePair("Hmong", "hmn"),
                MakePair("Huallaga Huánuco Quechua", "qub"),
                MakePair("Huastec", "hus"),
                MakePair("Huli", "hui"),
                MakePair("Hungarian", "hu"),
                MakePair("Iban", "iba"),
                MakePair("Ibibio", "ibb"),
                MakePair("Icelandic", "is"),
                MakePair("Ido", "io"),
                MakePair("Igbo", "ig"),
                MakePair("Iloko", "ilo"),
                MakePair("Imbabura Highland Quichua", "qvi"),
                MakePair("Indonesian", "id"),
                MakePair("Inga", "inb"),
                MakePair("Inuktitut", "iu"),
                MakePair("Irish", "ga"),
                MakePair("Isoko", "iso"),
                MakePair("Italian", "it"),
                MakePair("Iu Mien", "ium"),
                MakePair("Izii", "izz"),
                MakePair("Jamaican Creole English", "jam"),
                MakePair("Japanese", "ja"),
                MakePair("Javanese", "jv"),
                MakePair("K'iche'", "quc"),
                MakePair("Kabardian", "kbd"),
                MakePair("Kabiyè", "kbp"),
                MakePair("Kachin", "kac"),
                MakePair("Kadazan Dusun", "dtp"),
                MakePair("Kalaallisut", "kl"),
                MakePair("Kalmyk", "xal"),
                MakePair("Kannada", "kn"),
                MakePair("Kanuri", "kr"),
                MakePair("Kaqchikel", "cak"),
                MakePair("Kara-Kalpak", "kaa"),
                MakePair("Karachay-Balkar", "krc"),
                MakePair("Kashmiri", "ks"),
                MakePair("Kazakh", "kk"),
                MakePair("Kedah Malay", "meo"),
                MakePair("Kekchí", "kek"),
                MakePair("Keley-I Kallahan", "ify"),
                MakePair("Khakas", "kjh"),
                MakePair("Khasi", "kha"),
                MakePair("Khmer", "km"),
                MakePair("Khmu", "kjg"),
                MakePair("Kimbundu", "kmb"),
                MakePair("Kinyarwanda", "rw"),
                MakePair("Kituba", "ktu"),
                MakePair("Klingon", "tlh"),
                MakePair("Kok Borok", "trp"),
                MakePair("Komi", "kv"),
                MakePair("Komi-Permyak", "koi"),
                MakePair("Kongo", "kg"),
                MakePair("Korean", "ko"),
                MakePair("Kosraean", "kos"),
                MakePair("Krio", "kri"),
                MakePair("Kuanua", "ksd"),
                MakePair("Kuanyama", "kj"),
                MakePair("Kumyk", "kum"),
                MakePair("Kupang Malay", "mkn"),
                MakePair("Kurdish", "ku"),
                MakePair("Kurdish, Sorani", "ckb"),
                MakePair("Kyrgyz", "ky"),
                MakePair("Lahu", "lhu"),
                MakePair("Lambayeque Quechua", "quf"),
                MakePair("Lango", "laj"),
                MakePair("Lao", "lo"),
                MakePair("Latgalian", "ltg"),
                MakePair("Latin", "la"),
                MakePair("Latvian", "lv"),
                MakePair("Ligurian", "lij"),
                MakePair("Limburgan", "li"),
                MakePair("Lingala", "ln"),
                MakePair("Lithuanian", "lt"),
                MakePair("Lombard", "lmo"),
                MakePair("Low German", "nds"),
                MakePair("Luba-Katanga", "lu"),
                MakePair("Lushai", "lus"),
                MakePair("Luxembourgish", "lb"),
                MakePair("Maasina Fulfulde", "ffm"),
                MakePair("Macedonian", "mk"),
                MakePair("Madurese", "mad"),
                MakePair("Magahi", "mag"),
                MakePair("Maithili", "mai"),
                MakePair("Makasar", "mak"),
                MakePair("Makhuwa-Meetto", "mgh"),
                MakePair("Malagasy", "mg"),
                MakePair("Malay", "ms"),
                MakePair("Malayalam", "ml"),
                MakePair("Maltese", "mt"),
                MakePair("Mam", "mam"),
                MakePair("Manggarai", "mqy"),
                MakePair("Manipuri", "mni"),
                MakePair("Manx", "gv"),
                MakePair("Mapuche", "arn"),
                MakePair("Maranao", "mrw"),
                MakePair("Marathi", "mr"),
                MakePair("Mari", "chm"),
                MakePair("Marshallese", "mh"),
                MakePair("Masai", "mas"),
                MakePair("Masbatenyo", "msb"),
                MakePair("Matigsalug Manobo", "mbt"),
                MakePair("Minangkabau", "min"),
                MakePair("Mirandese", "mwl"),
                MakePair("Moksha", "mdf"),
                MakePair("Mongolian", "mn"),
                MakePair("Morisyen", "mfe"),
                MakePair("Moroccan Arabic", "ary"),
                MakePair("Motu", "meu"),
                MakePair("Mutu", "tuc"),
                MakePair("Mískito", "miq"),
                MakePair("Māori", "mi"),
                MakePair("Nande", "nnb"),
                MakePair("Nandi", "niq"),
                MakePair("Navajo", "nv"),
                MakePair("Nepal Bhasa", "new"),
                MakePair("Nepali", "ne"),
                MakePair("Ngaju", "nij"),
                MakePair("Ngäbere", "gym"),
                MakePair("Nias", "nia"),
                MakePair("Nigerian Fulfulde", "fuv"),
                MakePair("Nogai", "nog"),
                MakePair("North Sámi", "se"),
                MakePair("Northern Emberá", "emp"),
                MakePair("Northern Luri", "lrc"),
                MakePair("Northern Pastaza Quichua", "qvz"),
                MakePair("Northern Sotho", "nso"),
                MakePair("Norwegian", "no"),
                MakePair("Norwegian Nynorsk", "nn"),
                MakePair("Nuer", "nus"),
                MakePair("Nung", "nut"),
                MakePair("Nyanja", "ny"),
                MakePair("Nyungwe", "nyu"),
                MakePair("Nzima", "nzi"),
                MakePair("Obolo", "ann"),
                MakePair("Occitan", "oc"),
                MakePair("Odia", "or"),
                MakePair("Ojibwa", "oj"),
                MakePair("Old English", "ang"),
                MakePair("Oromo", "om"),
                MakePair("Ossetic", "os"),
                MakePair("Paite Chin", "pck"),
                MakePair("Palauan", "pau"),
                MakePair("Pangasinan", "pag"),
                MakePair("Papiamento", "pap"),
                MakePair("Pashto", "ps"),
                MakePair("Persian", "fa"),
                MakePair("Pijin", "pis"),
                MakePair("Pohnpeian", "pon"),
                MakePair("Polish", "pl"),
                MakePair("Popti'", "jac"),
                MakePair("Portuguese", "pt"),
                MakePair("Punjabi", "pa"),
                MakePair("Quechua", "qu"),
                MakePair("Querétaro Otomi", "otq"),
                MakePair("Rajasthani", "raj"),
                MakePair("Rakhine", "rki"),
                MakePair("Rawa", "rwo"),
                MakePair("Romanian", "ro"),
                MakePair("Romansh", "rm"),
                MakePair("Romany", "rom"),
                MakePair("Rundi", "rn"),
                MakePair("Russian", "ru"),
                MakePair("Réunion Creole French", "rcf"),
                MakePair("S'gaw Karen", "ksw"),
                MakePair("Sabah Malay", "msi"),
                MakePair("Sabu", "hvn"),
                MakePair("Saint Lucian Creole French", "acf"),
                MakePair("Sakha", "sah"),
                MakePair("Samoan", "sm"),
                MakePair("San Blas Kuna", "cuk"),
                MakePair("Sangir", "sxn"),
                MakePair("Sango", "sg"),
                MakePair("Sanskrit", "sa"),
                MakePair("Saraiki", "skr"),
                MakePair("Saramaccan", "srm"),
                MakePair("Sardinian", "sc"),
                MakePair("Saterfriesisch", "stq"),
                MakePair("Scottish Gaelic", "gd"),
                MakePair("Sena", "seh"),
                MakePair("Serbian", "sr"),
                MakePair("Serbo-Croatian", "sh"),
                MakePair("Seselwa Creole French", "crs"),
                MakePair("Shan", "shn"),
                MakePair("Shipibo-Konibo", "shp"),
                MakePair("Shona", "sn"),
                MakePair("Shuar", "jiv"),
                MakePair("Sicilian", "scn"),
                MakePair("Silesian", "szl"),
                MakePair("Simte", "smt"),
                MakePair("Sindhi", "sd"),
                MakePair("Sinhala", "si"),
                MakePair("Slovak", "sk"),
                MakePair("Slovenian", "sl"),
                MakePair("Somali", "so"),
                MakePair("South Bolivian Quechua", "quh"),
                MakePair("South Ndebele", "nr"),
                MakePair("Southern Altai", "alt"),
                MakePair("Southern Pastaza Quechua", "qup"),
                MakePair("Southern Sotho", "st"),
                MakePair("Spanish", "es"),
                MakePair("Sranan Tongo", "srn"),
                MakePair("Sundanese", "su"),
                MakePair("Sunwar", "suz"),
                MakePair("Supyire Senoufo", "spp"),
                MakePair("Susu", "sus"),
                MakePair("Swahili", "sw"),
                MakePair("Swati", "ss"),
                MakePair("Swedish", "sv"),
                MakePair("Swiss German", "gsw"),
                MakePair("Tabassaran", "tab"),
                MakePair("Tajik", "tg"),
                MakePair("Takestani", "tks"),
                MakePair("Tamasheq", "taq"),
                MakePair("Tamil", "ta"),
                MakePair("Tandroy-Mahafaly Malagasy", "tdx"),
                MakePair("Tatar", "tt"),
                MakePair("Tausug", "tsg"),
                MakePair("Telugu", "te"),
                MakePair("Termanu", "twu"),
                MakePair("Teso", "teo"),
                MakePair("Tetela", "tll"),
                MakePair("Tetum", "tet"),
                MakePair("Thai", "th"),
                MakePair("Tibetan", "bo"),
                MakePair("Ticuna", "tca"),
                MakePair("Tigrinya", "ti"),
                MakePair("Tiv", "tiv"),
                MakePair("Tojolabal", "toj"),
                MakePair("Tongan", "to"),
                MakePair("Toraja-Sa'dan", "sda"),
                MakePair("Tsonga", "ts"),
                MakePair("Tswa", "tsc"),
                MakePair("Tswana", "tn"),
                MakePair("Tulu", "tcy"),
                MakePair("Turkish", "tr"),
                MakePair("Turkmen", "tk"),
                MakePair("Tuvalu", "tvl"),
                MakePair("Tuvinian", "tyv"),
                MakePair("Tz'utujil", "tzj"),
                MakePair("Tzeltal", "tzh"),
                MakePair("Tzotzil", "tzo"),
                MakePair("Tày", "tyz"),
                MakePair("Udmurt", "udm"),
                MakePair("Ukrainian", "uk"),
                MakePair("Uma", "ppk"),
                MakePair("Umbu-Ungu", "ubu"),
                MakePair("Urdu", "ur"),
                MakePair("Uyghur", "ug"),
                MakePair("Uzbek", "uz"),
                MakePair("Venda", "ve"),
                MakePair("Venetian", "vec"),
                MakePair("Vietnamese", "vi"),
                MakePair("Walloon", "wa"),
                MakePair("Waray", "war"),
                MakePair("Wayuu", "guc"),
                MakePair("Welsh", "cy"),
                MakePair("Western Frisian", "fy"),
                MakePair("Western Kanjobal", "knj"),
                MakePair("Western Mari", "mrj"),
                MakePair("Wolaytta", "wal"),
                MakePair("Wolof", "wo"),
                MakePair("Woun Meu", "noa"),
                MakePair("Wu Chinese", "wuu"),
                MakePair("Xhosa", "xh"),
                MakePair("Yapese", "yap"),
                MakePair("Yiddish", "yi"),
                MakePair("Yoruba", "yo"),
                MakePair("Yucateco", "yua"),
                MakePair("Zande", "zne"),
                MakePair("Zapotec", "zap"),
                MakePair("Zarma", "dje"),
                MakePair("Zaza", "zza"),
                MakePair("Zulu", "zu"),
            };
        }

        /// <summary>
        /// True if <paramref name="code"/> is a language MADLAD has a control token for.
        /// </summary>
        public static bool IsSupported(string code)
        {
            return !string.IsNullOrEmpty(code) && Codes.Contains(code);
        }

        private static TranslationPair MakePair(string name, string code)
        {
            // Keep a two-letter code where ISO 639 has one - it is what the line-break and
            // text-split rules match on - and fall back to the MADLAD code itself, never to an
            // empty string.
            var twoLetter = code.Length == 2 ? code : Iso639Dash2LanguageCode.GetTwoLetterCodeFromThreeLetterCode(code);

            return new TranslationPair(name, code, string.IsNullOrEmpty(twoLetter) ? code : twoLetter);
        }
    }
}
