using Avalonia.Controls;
using Avalonia.Input;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Nikse.SubtitleEdit.Logic.Config;

namespace Nikse.SubtitleEdit.Features.Video.OpenFromUrl;

public enum OpenFromUrlMode
{
    OpenOnline,
    DownloadAndOpen,
}

public partial class OpenFromUrlViewModel : ObservableObject
{
    [ObservableProperty] private string _url;
    [ObservableProperty] private bool _downloadVideo;
    [ObservableProperty] private bool _downloadSubtitles;
    [ObservableProperty] private bool _includeAutoGeneratedSubtitles;

    public Window? Window { get; set; }

    public OpenFromUrlMode? SelectedMode { get; private set; }

    public bool OkPressed => SelectedMode != null;

    public OpenFromUrlViewModel()
    {
        Url = string.Empty;
        DownloadVideo = Se.Settings.Video.OpenFromUrlDownloadVideo;
        DownloadSubtitles = Se.Settings.Video.OpenFromUrlDownloadSubtitles;
        IncludeAutoGeneratedSubtitles = Se.Settings.Video.OpenFromUrlIncludeAutoGeneratedSubtitles;
    }

    private void SaveSettings()
    {
        Se.Settings.Video.OpenFromUrlDownloadVideo = DownloadVideo;
        Se.Settings.Video.OpenFromUrlDownloadSubtitles = DownloadSubtitles;
        Se.Settings.Video.OpenFromUrlIncludeAutoGeneratedSubtitles = IncludeAutoGeneratedSubtitles;
    }

    [RelayCommand]
    private void OpenOnline()
    {
        if (string.IsNullOrWhiteSpace(Url))
        {
            return;
        }

        SaveSettings();
        SelectedMode = OpenFromUrlMode.OpenOnline;
        Window?.Close();
    }

    [RelayCommand]
    private void DownloadAndOpen()
    {
        if (string.IsNullOrWhiteSpace(Url) || (!DownloadVideo && !DownloadSubtitles))
        {
            return;
        }

        SaveSettings();
        SelectedMode = OpenFromUrlMode.DownloadAndOpen;
        Window?.Close();
    }

    [RelayCommand]
    private void Cancel()
    {
        Window?.Close();
    }

    internal void OnKeyDown(KeyEventArgs e)
    {
        if (e.Key == Key.Escape)
        {
            e.Handled = true;
            Window?.Close();
        }
    }
}
