using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Windows.Forms;
using Nikse.SubtitleEdit.Core;
using Nikse.SubtitleEdit.Logic;
using Nikse.SubtitleEdit.Logic.SubtitleFormats;

namespace Nikse.SubtitleEdit.Forms
{
    public sealed partial class Statistics : PositionAndSizeForm
    {
        private Subtitle _subtitle;
        private SubtitleFormat _format;
        private LanguageStructure.Statistics _l;
        private string _mostUsedLines;
        private string _general;
        private string _mostUsedWords;
        const string WriteFormat = @"File generated by: Subtitle Edit
http://www.nikse.dk/subtitleedit/
https://github.com/SubtitleEdit/subtitleedit
============================= General =============================
{0}
============================= Most Used Words =============================
{1}
============================= Most Used Lines =============================
{2}";
        public Statistics(Subtitle subtitle, string fileName, SubtitleFormat format)
        {
            InitializeComponent();

            _subtitle = subtitle;
            _format = format;

            _l = Configuration.Settings.Language.Statistics;
            if (string.IsNullOrEmpty(fileName))
                Text = _l.Title;
            else
                Text = string.Format(_l.TitleWithFileName, fileName);
            groupBoxGeneral.Text = _l.GeneralStatistics;
            groupBoxMostUsed.Text = _l.MostUsed;
            labelMostUsedWords.Text = _l.MostUsedWords;
            labelMostUsedLines.Text = _l.MostUsedLines;
            buttonExport.Text = _l.Export;
            buttonOK.Text = Configuration.Settings.Language.General.Ok;
            Utilities.FixLargeFonts(this, buttonOK);

            CalculateGeneralStatistics();
            {
                textBoxGeneral.Text = _general;
                textBoxGeneral.SelectionStart = 0;
                textBoxGeneral.SelectionLength = 0;
                textBoxGeneral.ScrollToCaret();
            }
            CalculateMostUsedWords();
            {
                textBoxMostUsedWords.Text = _mostUsedWords;
            }
            CalculateMostUsedLines();
            {
                textBoxMostUsedLines.Text = _mostUsedLines;
            }
        }

        private void CalculateGeneralStatistics()
        {
            if (_subtitle == null || _subtitle.Paragraphs.Count == 0)
            {
                textBoxGeneral.Text = _l.NothingFound;
                return;
            }

            var allText = new StringBuilder();
            int minimumLineLength = 99999999;
            int maximumLineLength = 0;
            long totalLineLength = 0;
            int minimumSingleLineLength = 99999999;
            int maximumSingleLineLength = 0;
            long totalSingleLineLength = 0;
            long totalSingleLines = 0;
            double minimumDuration = 100000000;
            double maximumDuration = 0;
            double totalDuration = 0;
            double minimumCharsSec = 100000000;
            double maximumCharsSec = 0;
            double totalCharsSec = 0;
            foreach (Paragraph p in _subtitle.Paragraphs)
            {
                allText.Append(p.Text);

                int len = p.Text.Length;
                if (len < minimumLineLength)
                    minimumLineLength = len;
                if (len > maximumLineLength)
                    maximumLineLength = len;
                totalLineLength += len;

                double duration = p.Duration.TotalMilliseconds;
                if (duration < minimumDuration)
                    minimumDuration = duration;
                if (duration > maximumDuration)
                    maximumDuration = duration;
                totalDuration += duration;

                var charsSec = Utilities.GetCharactersPerSecond(p);
                if (charsSec < minimumCharsSec)
                    minimumCharsSec = charsSec;
                if (charsSec > maximumCharsSec)
                    maximumCharsSec = charsSec;
                totalCharsSec += charsSec;

                foreach (string line in p.Text.SplitToLines())
                {
                    len = line.Length;
                    if (len < minimumSingleLineLength)
                        minimumSingleLineLength = len;
                    if (len > maximumSingleLineLength)
                        maximumSingleLineLength = len;
                    totalSingleLineLength += len;
                    totalSingleLines++;
                }
            }

            var sb = new StringBuilder();
            int sourceLength = _subtitle.ToText(_format).Length;
            sb.AppendLine(string.Format(_l.NumberOfLinesX, _subtitle.Paragraphs.Count));
            sb.AppendLine(string.Format(_l.LengthInFormatXinCharactersY, _format.FriendlyName, sourceLength));
            sb.AppendLine(string.Format(_l.NumberOfCharactersInTextOnly, allText.Length));
            sb.AppendLine(string.Format(_l.TotalCharsPerSecond, HtmlUtil.RemoveHtmlTags(allText.ToString()).Length / (totalDuration / TimeCode.BaseUnit)));
            sb.AppendLine(string.Format(_l.NumberOfItalicTags, Utilities.CountTagInText(allText.ToString().ToLower(), "<i>")));
            sb.AppendLine(string.Format(_l.NumberOfBoldTags, Utilities.CountTagInText(allText.ToString().ToLower(), "<b>")));
            sb.AppendLine(string.Format(_l.NumberOfUnderlineTags, Utilities.CountTagInText(allText.ToString().ToLower(), "<u>")));
            sb.AppendLine(string.Format(_l.NumberOfFontTags, Utilities.CountTagInText(allText.ToString().ToLower(), "<font ")));
            sb.AppendLine(string.Format(_l.NumberOfAlignmentTags, Utilities.CountTagInText(allText.ToString().ToLower(), "{\\a")));
            sb.AppendLine();
            sb.AppendLine(string.Format(_l.LineLengthMinimum, minimumLineLength));
            sb.AppendLine(string.Format(_l.LineLengthMaximum, maximumLineLength));
            sb.AppendLine(string.Format(_l.LineLengthAverage, totalLineLength / _subtitle.Paragraphs.Count));
            sb.AppendLine(string.Format(_l.LinesPerSubtitleAverage, (((double)totalSingleLines) / _subtitle.Paragraphs.Count)));
            sb.AppendLine();
            sb.AppendLine(string.Format(_l.SingleLineLengthMinimum, minimumSingleLineLength));
            sb.AppendLine(string.Format(_l.SingleLineLengthMaximum, maximumSingleLineLength));
            sb.AppendLine(string.Format(_l.SingleLineLengthAverage, totalSingleLineLength / totalSingleLines));
            sb.AppendLine();
            sb.AppendLine(string.Format(_l.DurationMinimum, minimumDuration / TimeCode.BaseUnit));
            sb.AppendLine(string.Format(_l.DurationMaximum, maximumDuration / TimeCode.BaseUnit));
            sb.AppendLine(string.Format(_l.DurationAverage, totalDuration / _subtitle.Paragraphs.Count / TimeCode.BaseUnit));
            sb.AppendLine();
            sb.AppendLine(string.Format(_l.CharactersPerSecondMinimum, minimumCharsSec));
            sb.AppendLine(string.Format(_l.CharactersPerSecondMaximum, maximumCharsSec));
            sb.AppendLine(string.Format(_l.CharactersPerSecondAverage, totalCharsSec / _subtitle.Paragraphs.Count));
            sb.AppendLine();
            _general = sb.ToString().Trim();
        }

        private void Statistics_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Escape)
                DialogResult = DialogResult.Cancel;
            else if (e.KeyData == (Keys.Control | Keys.C))
                Clipboard.SetText(string.Format(WriteFormat, _general, _mostUsedWords, _mostUsedLines), TextDataFormat.UnicodeText);
        }

        private static void MostUsedWordsAdd(Dictionary<string, string> hashtable, string lastLine)
        {
            if (lastLine.Contains("< "))
                lastLine = HtmlUtil.FixInvalidItalicTags(lastLine);
            lastLine = lastLine.Trim('\'');
            lastLine = lastLine.Replace("\"", "");
            lastLine = lastLine.Replace("<i>", "");
            lastLine = lastLine.Replace("</i>", ".");
            lastLine = lastLine.Replace("<I>", "");
            lastLine = lastLine.Replace("</I>", ".");
            lastLine = lastLine.Replace("<b>", "");
            lastLine = lastLine.Replace("</b>", ".");
            lastLine = lastLine.Replace("<B>", "");
            lastLine = lastLine.Replace("</B>", ".");
            lastLine = lastLine.Replace("<u>", "");
            lastLine = lastLine.Replace("</u>", ".");
            lastLine = lastLine.Replace("<U>", "");
            lastLine = lastLine.Replace("</U>", ".");

            var idx = lastLine.IndexOf("<font", StringComparison.OrdinalIgnoreCase);
            var error = false;
            while (idx >= 0)
            {
                var endIdx = lastLine.IndexOf('>', idx + 5);
                if (endIdx < idx)
                {
                    error = !error;
                    break;
                }
                endIdx++;
                lastLine = lastLine.Remove(idx, (endIdx - idx));
                idx = lastLine.IndexOf("<font", StringComparison.OrdinalIgnoreCase);
            }
            if (!error)
                lastLine = lastLine.Replace("</font>", ".");

            string[] words = lastLine.Split(new[] { ' ', ',', '!', '?', '.', ':', ';', '-', '_', '@', '<', '>', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' }, StringSplitOptions.RemoveEmptyEntries);

            foreach (string word in words)
            {
                string s = word.Trim();

                if (s.Length > 1 && hashtable.ContainsKey(s))
                {
                    int hits = int.Parse(hashtable[s]);
                    hits++;
                    hashtable[s] = hits.ToString(CultureInfo.InvariantCulture);
                }
                else if (s.Length > 1)
                {
                    hashtable.Add(s, "1");
                }
            }
        }

        private static void MostUsedLinesAdd(Dictionary<string, string> hashtable, string lastLine)
        {
            lastLine = lastLine.Trim('\'');
            lastLine = lastLine.Replace("\"", "");
            lastLine = lastLine.Replace("<i>", "");
            lastLine = lastLine.Replace("</i>", ".");
            lastLine = lastLine.Replace("<I>", "");
            lastLine = lastLine.Replace("</I>", ".");
            lastLine = lastLine.Replace("<b>", "");
            lastLine = lastLine.Replace("</b>", ".");
            lastLine = lastLine.Replace("<B>", "");
            lastLine = lastLine.Replace("</B>", ".");
            lastLine = lastLine.Replace("<u>", "");
            lastLine = lastLine.Replace("</u>", ".");
            lastLine = lastLine.Replace("<U>", "");
            lastLine = lastLine.Replace("</U>", ".");
            lastLine = lastLine.Replace('!', '.');
            lastLine = lastLine.Replace('?', '.');
            lastLine = lastLine.Replace("...", ".");
            lastLine = lastLine.Replace("..", ".");
            lastLine = lastLine.Replace('-', ' ');
            lastLine = lastLine.FixExtraSpaces();
            string[] lines = lastLine.Split('.');

            foreach (string line in lines)
            {
                string s = line.Trim();

                if (hashtable.ContainsKey(s))
                {
                    int hits = int.Parse(hashtable[s]);
                    hits++;
                    hashtable[s] = hits.ToString(CultureInfo.InvariantCulture);
                }
                else if (s.Length > 0 && s.Contains(' '))
                {
                    hashtable.Add(s, "1");
                }
            }
        }

        private void CalculateMostUsedWords()
        {
            var hashtable = new Dictionary<string, string>();

            foreach (Paragraph p in _subtitle.Paragraphs)
                MostUsedWordsAdd(hashtable, p.Text);

            var sortedTable = new SortedDictionary<string, string>();
            foreach (KeyValuePair<string, string> item in hashtable)
            {
                if (int.Parse(item.Value) > 1)
                {
                    string s = item.Value;
                    while (s.Length < 4)
                        s = "0" + s;
                    sortedTable.Add(s + "_" + item.Key, item.Value + ": " + item.Key);
                }
            }

            var sb = new StringBuilder();
            if (sortedTable.Count > 0)
            {
                string temp = "";
                foreach (KeyValuePair<string, string> item in sortedTable)
                {
                    temp = item.Value + Environment.NewLine + temp;
                }
                sb.AppendLine(temp);
            }
            else
            {
                sb.AppendLine(_l.NothingFound);
            }
            _mostUsedWords = sb.ToString();
        }

        private void CalculateMostUsedLines()
        {
            var hashtable = new Dictionary<string, string>();

            foreach (Paragraph p in _subtitle.Paragraphs)
                MostUsedLinesAdd(hashtable, p.Text.Replace(Environment.NewLine, " ").Replace("  ", " "));

            SortedDictionary<string, string> sortedTable = new SortedDictionary<string, string>();
            foreach (KeyValuePair<string, string> item in hashtable)
            {
                if (int.Parse(item.Value) > 1)
                {
                    string s = item.Value;
                    while (s.Length < 4)
                        s = "0" + s;
                    sortedTable.Add(s + "_" + item.Key, item.Value + ": " + item.Key);
                }
            }

            var sb = new StringBuilder();
            if (sortedTable.Count > 0)
            {
                string temp = "";
                foreach (KeyValuePair<string, string> item in sortedTable)
                {
                    temp = item.Value + Environment.NewLine + temp;
                }
                sb.AppendLine(temp);
            }
            else
            {
                sb.AppendLine(_l.NothingFound);
            }
            _mostUsedLines = sb.ToString();
        }

        private void buttonOK_Click(object sender, EventArgs e)
        {
            DialogResult = DialogResult.OK;
        }

        private void buttonExport_Click(object sender, EventArgs e)
        {
            var saveFile = new SaveFileDialog { Filter = "Text files (*.txt)|*.txt|NFO files (*.nfo)|*.nfo" };
            if (saveFile.ShowDialog() == DialogResult.OK)
            {
                string fileName = saveFile.FileName;
                var statistic = string.Format(WriteFormat, _general, _mostUsedWords, _mostUsedLines);
                System.IO.File.WriteAllText(fileName, statistic);
            }
        }

    }
}