//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikse.SubtitleEdit.SeNetworkService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeSequence", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SeSequence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IndexField;
        
        private int StartMillisecondsField;
        
        private int EndMillisecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StartMilliseconds {
            get {
                return this.StartMillisecondsField;
            }
            set {
                if ((this.StartMillisecondsField.Equals(value) != true)) {
                    this.StartMillisecondsField = value;
                    this.RaisePropertyChanged("StartMilliseconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int EndMilliseconds {
            get {
                return this.EndMillisecondsField;
            }
            set {
                if ((this.EndMillisecondsField.Equals(value) != true)) {
                    this.EndMillisecondsField = value;
                    this.RaisePropertyChanged("EndMilliseconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SeUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        private System.DateTime LastActivityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime LastActivity {
            get {
                return this.LastActivityField;
            }
            set {
                if ((this.LastActivityField.Equals(value) != true)) {
                    this.LastActivityField = value;
                    this.RaisePropertyChanged("LastActivity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeUpdate", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SeUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Nikse.SubtitleEdit.SeNetworkService.SeUser UserField;
        
        private int IndexField;
        
        private int StartMillisecondsField;
        
        private int EndMillisecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUser User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StartMilliseconds {
            get {
                return this.StartMillisecondsField;
            }
            set {
                if ((this.StartMillisecondsField.Equals(value) != true)) {
                    this.StartMillisecondsField = value;
                    this.RaisePropertyChanged("StartMilliseconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int EndMilliseconds {
            get {
                return this.EndMillisecondsField;
            }
            set {
                if ((this.EndMillisecondsField.Equals(value) != true)) {
                    this.EndMillisecondsField = value;
                    this.RaisePropertyChanged("EndMilliseconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeNetworkService.SeServiceSoap")]
    public interface SeServiceSoap {
        
        // CODEGEN: Generating message contract since element name sessionKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Start", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.StartResponse Start(Nikse.SubtitleEdit.SeNetworkService.StartRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Join", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.JoinResponse Join(Nikse.SubtitleEdit.SeNetworkService.JoinRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Leave", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.LeaveResponse Leave(Nikse.SubtitleEdit.SeNetworkService.LeaveRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLines", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.DeleteLinesResponse DeleteLines(Nikse.SubtitleEdit.SeNetworkService.DeleteLinesRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertLine", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.InsertLineResponse InsertLine(Nikse.SubtitleEdit.SeNetworkService.InsertLineRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLine", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.UpdateLineResponse UpdateLine(Nikse.SubtitleEdit.SeNetworkService.UpdateLineRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.SendMessageResponse SendMessage(Nikse.SubtitleEdit.SeNetworkService.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdates", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.GetUpdatesResponse GetUpdates(Nikse.SubtitleEdit.SeNetworkService.GetUpdatesRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubtitle", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.GetSubtitleResponse GetSubtitle(Nikse.SubtitleEdit.SeNetworkService.GetSubtitleRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOriginalSubtitle", ReplyAction="*")]
        Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleResponse GetOriginalSubtitle(Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Start", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.StartRequestBody Body;
        
        public StartRequest() {
        }
        
        public StartRequest(Nikse.SubtitleEdit.SeNetworkService.StartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Nikse.SubtitleEdit.SeNetworkService.SeSequence[] subtitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Nikse.SubtitleEdit.SeNetworkService.SeSequence[] originalSubtitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fileName;
        
        public StartRequestBody() {
        }
        
        public StartRequestBody(string sessionKey, string userName, Nikse.SubtitleEdit.SeNetworkService.SeSequence[] subtitle, Nikse.SubtitleEdit.SeNetworkService.SeSequence[] originalSubtitle, string fileName) {
            this.sessionKey = sessionKey;
            this.userName = userName;
            this.subtitle = subtitle;
            this.originalSubtitle = originalSubtitle;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.StartResponseBody Body;
        
        public StartResponse() {
        }
        
        public StartResponse(Nikse.SubtitleEdit.SeNetworkService.StartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUser StartResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public StartResponseBody() {
        }
        
        public StartResponseBody(Nikse.SubtitleEdit.SeNetworkService.SeUser StartResult, string message) {
            this.StartResult = StartResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Join", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.JoinRequestBody Body;
        
        public JoinRequest() {
        }
        
        public JoinRequest(Nikse.SubtitleEdit.SeNetworkService.JoinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        public JoinRequestBody() {
        }
        
        public JoinRequestBody(string sessionId, string userName) {
            this.sessionId = sessionId;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JoinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JoinResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.JoinResponseBody Body;
        
        public JoinResponse() {
        }
        
        public JoinResponse(Nikse.SubtitleEdit.SeNetworkService.JoinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JoinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUser[] JoinResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public JoinResponseBody() {
        }
        
        public JoinResponseBody(Nikse.SubtitleEdit.SeNetworkService.SeUser[] JoinResult, string message) {
            this.JoinResult = JoinResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leave", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.LeaveRequestBody Body;
        
        public LeaveRequest() {
        }
        
        public LeaveRequest(Nikse.SubtitleEdit.SeNetworkService.LeaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        public LeaveRequestBody() {
        }
        
        public LeaveRequestBody(string sessionId, string userName) {
            this.sessionId = sessionId;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.LeaveResponseBody Body;
        
        public LeaveResponse() {
        }
        
        public LeaveResponse(Nikse.SubtitleEdit.SeNetworkService.LeaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LeaveResponseBody {
        
        public LeaveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLinesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLines", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.DeleteLinesRequestBody Body;
        
        public DeleteLinesRequest() {
        }
        
        public DeleteLinesRequest(Nikse.SubtitleEdit.SeNetworkService.DeleteLinesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteLinesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Nikse.SubtitleEdit.SeNetworkService.ArrayOfInt indices;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUser user;
        
        public DeleteLinesRequestBody() {
        }
        
        public DeleteLinesRequestBody(string sessionId, Nikse.SubtitleEdit.SeNetworkService.ArrayOfInt indices, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            this.sessionId = sessionId;
            this.indices = indices;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLinesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.DeleteLinesResponseBody Body;
        
        public DeleteLinesResponse() {
        }
        
        public DeleteLinesResponse(Nikse.SubtitleEdit.SeNetworkService.DeleteLinesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteLinesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteLinesResult;
        
        public DeleteLinesResponseBody() {
        }
        
        public DeleteLinesResponseBody(bool DeleteLinesResult) {
            this.DeleteLinesResult = DeleteLinesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertLine", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.InsertLineRequestBody Body;
        
        public InsertLineRequest() {
        }
        
        public InsertLineRequest(Nikse.SubtitleEdit.SeNetworkService.InsertLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int startMilliseconds;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int endMilliseconds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUser user;
        
        public InsertLineRequestBody() {
        }
        
        public InsertLineRequestBody(string sessionId, int index, int startMilliseconds, int endMilliseconds, string text, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            this.sessionId = sessionId;
            this.index = index;
            this.startMilliseconds = startMilliseconds;
            this.endMilliseconds = endMilliseconds;
            this.text = text;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertLineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.InsertLineResponseBody Body;
        
        public InsertLineResponse() {
        }
        
        public InsertLineResponse(Nikse.SubtitleEdit.SeNetworkService.InsertLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertLineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertLineResult;
        
        public InsertLineResponseBody() {
        }
        
        public InsertLineResponseBody(bool InsertLineResult) {
            this.InsertLineResult = InsertLineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLine", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.UpdateLineRequestBody Body;
        
        public UpdateLineRequest() {
        }
        
        public UpdateLineRequest(Nikse.SubtitleEdit.SeNetworkService.UpdateLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Nikse.SubtitleEdit.SeNetworkService.SeSequence sequence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUser user;
        
        public UpdateLineRequestBody() {
        }
        
        public UpdateLineRequestBody(string sessionId, int index, Nikse.SubtitleEdit.SeNetworkService.SeSequence sequence, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            this.sessionId = sessionId;
            this.index = index;
            this.sequence = sequence;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.UpdateLineResponseBody Body;
        
        public UpdateLineResponse() {
        }
        
        public UpdateLineResponse(Nikse.SubtitleEdit.SeNetworkService.UpdateLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateLineResult;
        
        public UpdateLineResponseBody() {
        }
        
        public UpdateLineResponseBody(bool UpdateLineResult) {
            this.UpdateLineResult = UpdateLineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Nikse.SubtitleEdit.SeNetworkService.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUser user;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string sessionId, string text, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            this.sessionId = sessionId;
            this.text = text;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Nikse.SubtitleEdit.SeNetworkService.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(bool SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpdatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpdates", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.GetUpdatesRequestBody Body;
        
        public GetUpdatesRequest() {
        }
        
        public GetUpdatesRequest(Nikse.SubtitleEdit.SeNetworkService.GetUpdatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUpdatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime lastUpdateTime;
        
        public GetUpdatesRequestBody() {
        }
        
        public GetUpdatesRequestBody(string sessionId, string userName, System.DateTime lastUpdateTime) {
            this.sessionId = sessionId;
            this.userName = userName;
            this.lastUpdateTime = lastUpdateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpdatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpdatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.GetUpdatesResponseBody Body;
        
        public GetUpdatesResponse() {
        }
        
        public GetUpdatesResponse(Nikse.SubtitleEdit.SeNetworkService.GetUpdatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUpdatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.SeUpdate[] GetUpdatesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime newUpdateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int numberOfLines;
        
        public GetUpdatesResponseBody() {
        }
        
        public GetUpdatesResponseBody(Nikse.SubtitleEdit.SeNetworkService.SeUpdate[] GetUpdatesResult, string message, System.DateTime newUpdateTime, int numberOfLines) {
            this.GetUpdatesResult = GetUpdatesResult;
            this.message = message;
            this.newUpdateTime = newUpdateTime;
            this.numberOfLines = numberOfLines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubtitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubtitle", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.GetSubtitleRequestBody Body;
        
        public GetSubtitleRequest() {
        }
        
        public GetSubtitleRequest(Nikse.SubtitleEdit.SeNetworkService.GetSubtitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubtitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        public GetSubtitleRequestBody() {
        }
        
        public GetSubtitleRequestBody(string sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubtitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubtitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.GetSubtitleResponseBody Body;
        
        public GetSubtitleResponse() {
        }
        
        public GetSubtitleResponse(Nikse.SubtitleEdit.SeNetworkService.GetSubtitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubtitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.SeSequence[] GetSubtitleResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime updateTime;
        
        public GetSubtitleResponseBody() {
        }
        
        public GetSubtitleResponseBody(Nikse.SubtitleEdit.SeNetworkService.SeSequence[] GetSubtitleResult, string fileName, System.DateTime updateTime) {
            this.GetSubtitleResult = GetSubtitleResult;
            this.fileName = fileName;
            this.updateTime = updateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOriginalSubtitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOriginalSubtitle", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleRequestBody Body;
        
        public GetOriginalSubtitleRequest() {
        }
        
        public GetOriginalSubtitleRequest(Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOriginalSubtitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        public GetOriginalSubtitleRequestBody() {
        }
        
        public GetOriginalSubtitleRequestBody(string sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOriginalSubtitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOriginalSubtitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleResponseBody Body;
        
        public GetOriginalSubtitleResponse() {
        }
        
        public GetOriginalSubtitleResponse(Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOriginalSubtitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Nikse.SubtitleEdit.SeNetworkService.SeSequence[] GetOriginalSubtitleResult;
        
        public GetOriginalSubtitleResponseBody() {
        }
        
        public GetOriginalSubtitleResponseBody(Nikse.SubtitleEdit.SeNetworkService.SeSequence[] GetOriginalSubtitleResult) {
            this.GetOriginalSubtitleResult = GetOriginalSubtitleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeServiceSoapChannel : Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeServiceSoapClient : System.ServiceModel.ClientBase<Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap>, Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap {
        
        public SeServiceSoapClient() {
        }
        
        public SeServiceSoapClient(string endpointConfigurationName, object binding) : 
                base(endpointConfigurationName) {
        }
        
        public SeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.StartResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.Start(Nikse.SubtitleEdit.SeNetworkService.StartRequest request) {
            return base.Channel.Start(request);
        }
        
        public Nikse.SubtitleEdit.SeNetworkService.SeUser Start(string sessionKey, string userName, Nikse.SubtitleEdit.SeNetworkService.SeSequence[] subtitle, Nikse.SubtitleEdit.SeNetworkService.SeSequence[] originalSubtitle, string fileName, out string message) {
            Nikse.SubtitleEdit.SeNetworkService.StartRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.StartRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.StartRequestBody();
            inValue.Body.sessionKey = sessionKey;
            inValue.Body.userName = userName;
            inValue.Body.subtitle = subtitle;
            inValue.Body.originalSubtitle = originalSubtitle;
            inValue.Body.fileName = fileName;
            Nikse.SubtitleEdit.SeNetworkService.StartResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).Start(inValue);
            message = retVal.Body.message;
            return retVal.Body.StartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.JoinResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.Join(Nikse.SubtitleEdit.SeNetworkService.JoinRequest request) {
            return base.Channel.Join(request);
        }
        
        public Nikse.SubtitleEdit.SeNetworkService.SeUser[] Join(string sessionId, string userName, out string message) {
            Nikse.SubtitleEdit.SeNetworkService.JoinRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.JoinRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.JoinRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.userName = userName;
            Nikse.SubtitleEdit.SeNetworkService.JoinResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).Join(inValue);
            message = retVal.Body.message;
            return retVal.Body.JoinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.LeaveResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.Leave(Nikse.SubtitleEdit.SeNetworkService.LeaveRequest request) {
            return base.Channel.Leave(request);
        }
        
        public void Leave(string sessionId, string userName) {
            Nikse.SubtitleEdit.SeNetworkService.LeaveRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.LeaveRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.LeaveRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.userName = userName;
            Nikse.SubtitleEdit.SeNetworkService.LeaveResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).Leave(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.DeleteLinesResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.DeleteLines(Nikse.SubtitleEdit.SeNetworkService.DeleteLinesRequest request) {
            return base.Channel.DeleteLines(request);
        }
        
        public bool DeleteLines(string sessionId, Nikse.SubtitleEdit.SeNetworkService.ArrayOfInt indices, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            Nikse.SubtitleEdit.SeNetworkService.DeleteLinesRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.DeleteLinesRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.DeleteLinesRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.indices = indices;
            inValue.Body.user = user;
            Nikse.SubtitleEdit.SeNetworkService.DeleteLinesResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).DeleteLines(inValue);
            return retVal.Body.DeleteLinesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.InsertLineResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.InsertLine(Nikse.SubtitleEdit.SeNetworkService.InsertLineRequest request) {
            return base.Channel.InsertLine(request);
        }
        
        public bool InsertLine(string sessionId, int index, int startMilliseconds, int endMilliseconds, string text, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            Nikse.SubtitleEdit.SeNetworkService.InsertLineRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.InsertLineRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.InsertLineRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.index = index;
            inValue.Body.startMilliseconds = startMilliseconds;
            inValue.Body.endMilliseconds = endMilliseconds;
            inValue.Body.text = text;
            inValue.Body.user = user;
            Nikse.SubtitleEdit.SeNetworkService.InsertLineResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).InsertLine(inValue);
            return retVal.Body.InsertLineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.UpdateLineResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.UpdateLine(Nikse.SubtitleEdit.SeNetworkService.UpdateLineRequest request) {
            return base.Channel.UpdateLine(request);
        }
        
        public bool UpdateLine(string sessionId, int index, Nikse.SubtitleEdit.SeNetworkService.SeSequence sequence, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            Nikse.SubtitleEdit.SeNetworkService.UpdateLineRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.UpdateLineRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.UpdateLineRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.index = index;
            inValue.Body.sequence = sequence;
            inValue.Body.user = user;
            Nikse.SubtitleEdit.SeNetworkService.UpdateLineResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).UpdateLine(inValue);
            return retVal.Body.UpdateLineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.SendMessageResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.SendMessage(Nikse.SubtitleEdit.SeNetworkService.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public bool SendMessage(string sessionId, string text, Nikse.SubtitleEdit.SeNetworkService.SeUser user) {
            Nikse.SubtitleEdit.SeNetworkService.SendMessageRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.SendMessageRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.SendMessageRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.text = text;
            inValue.Body.user = user;
            Nikse.SubtitleEdit.SeNetworkService.SendMessageResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.GetUpdatesResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.GetUpdates(Nikse.SubtitleEdit.SeNetworkService.GetUpdatesRequest request) {
            return base.Channel.GetUpdates(request);
        }
        
        public Nikse.SubtitleEdit.SeNetworkService.SeUpdate[] GetUpdates(string sessionId, string userName, System.DateTime lastUpdateTime, out string message, out System.DateTime newUpdateTime, out int numberOfLines) {
            Nikse.SubtitleEdit.SeNetworkService.GetUpdatesRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.GetUpdatesRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.GetUpdatesRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.userName = userName;
            inValue.Body.lastUpdateTime = lastUpdateTime;
            Nikse.SubtitleEdit.SeNetworkService.GetUpdatesResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).GetUpdates(inValue);
            message = retVal.Body.message;
            newUpdateTime = retVal.Body.newUpdateTime;
            numberOfLines = retVal.Body.numberOfLines;
            return retVal.Body.GetUpdatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.GetSubtitleResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.GetSubtitle(Nikse.SubtitleEdit.SeNetworkService.GetSubtitleRequest request) {
            return base.Channel.GetSubtitle(request);
        }
        
        public Nikse.SubtitleEdit.SeNetworkService.SeSequence[] GetSubtitle(string sessionId, out string fileName, out System.DateTime updateTime) {
            Nikse.SubtitleEdit.SeNetworkService.GetSubtitleRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.GetSubtitleRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.GetSubtitleRequestBody();
            inValue.Body.sessionId = sessionId;
            Nikse.SubtitleEdit.SeNetworkService.GetSubtitleResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).GetSubtitle(inValue);
            fileName = retVal.Body.fileName;
            updateTime = retVal.Body.updateTime;
            return retVal.Body.GetSubtitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleResponse Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap.GetOriginalSubtitle(Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleRequest request) {
            return base.Channel.GetOriginalSubtitle(request);
        }
        
        public Nikse.SubtitleEdit.SeNetworkService.SeSequence[] GetOriginalSubtitle(string sessionId) {
            Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleRequest inValue = new Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleRequest();
            inValue.Body = new Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleRequestBody();
            inValue.Body.sessionId = sessionId;
            Nikse.SubtitleEdit.SeNetworkService.GetOriginalSubtitleResponse retVal = ((Nikse.SubtitleEdit.SeNetworkService.SeServiceSoap)(this)).GetOriginalSubtitle(inValue);
            return retVal.Body.GetOriginalSubtitleResult;
        }
    }
}
