<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><Compile Remove="TestLibSE/**/*.cs"/><Using Include="Xunit"/><PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1"/><PackageReference Include="xunit.v3" Version="3.2.2"/><PackageReference Include="xunit.runner.visualstudio" Version="3.1.5"/><ProjectReference Include="TestLibSE/TestLibSE.csproj"/></ItemGroup></Project>