using Nikse.SubtitleEdit.Core.Common;

namespace Nikse.SubtitleEdit.Core.AudioToText
{
    public class WhisperLanguage
    {
        public string Code => Iso639Dash2LanguageCode.GetTwoLetterCodeFromEnglishName(Name);
        public string Name { get; set; }

        public WhisperLanguage(string name)
        {
            Name = name;
        }

        public override string ToString()
        {
            return Name;
        }

        public static readonly WhisperLanguage[] Languages =
        {
            new WhisperLanguage("Afrikaans"),
            new WhisperLanguage("Albanian"),
            new WhisperLanguage("Amharic"),
            new WhisperLanguage("Arabic"),
            new WhisperLanguage("Armenian"),
            new WhisperLanguage("Assamese"),
            new WhisperLanguage("Azerbaijani"),
            new WhisperLanguage("Bashkir"),
            new WhisperLanguage("Basque"),
            new WhisperLanguage("Belarusian"),
            new WhisperLanguage("Bengali"),
            new WhisperLanguage("Bosnian"),
            new WhisperLanguage("Breton"),
            new WhisperLanguage("Bulgarian"),
            new WhisperLanguage("Burmese"),
            new WhisperLanguage("Castilian"),
            new WhisperLanguage("Catalan"),
            new WhisperLanguage("Chinese"),
            new WhisperLanguage("Croatian"),
            new WhisperLanguage("Czech"),
            new WhisperLanguage("Danish"),
            new WhisperLanguage("Dutch"),
            new WhisperLanguage("English"),
            new WhisperLanguage("Estonian"),
            new WhisperLanguage("Faroese"),
            new WhisperLanguage("Finnish"),
            new WhisperLanguage("Flemish"),
            new WhisperLanguage("French"),
            new WhisperLanguage("Galician"),
            new WhisperLanguage("Georgian"),
            new WhisperLanguage("German"),
            new WhisperLanguage("Greek"),
            new WhisperLanguage("Gujarati"),
            new WhisperLanguage("Haitian"),
            new WhisperLanguage("Haitian Creole"),
            new WhisperLanguage("Hausa"),
            new WhisperLanguage("Hawaiian"),
            new WhisperLanguage("Hebrew"),
            new WhisperLanguage("Hindi"),
            new WhisperLanguage("Hungarian"),
            new WhisperLanguage("Icelandic"),
            new WhisperLanguage("Indonesian"),
            new WhisperLanguage("Italian"),
            new WhisperLanguage("Japanese"),
            new WhisperLanguage("Javanese"),
            new WhisperLanguage("Kannada"),
            new WhisperLanguage("Kazakh"),
            new WhisperLanguage("Khmer"),
            new WhisperLanguage("Korean"),
            new WhisperLanguage("Lao"),
            new WhisperLanguage("Latin"),
            new WhisperLanguage("Latvian"),
            new WhisperLanguage("Letzeburgesch"),
            new WhisperLanguage("Lingala"),
            new WhisperLanguage("Lithuanian"),
            new WhisperLanguage("Luxembourgish"),
            new WhisperLanguage("Macedonian"),
            new WhisperLanguage("Malagasy"),
            new WhisperLanguage("Malay"),
            new WhisperLanguage("Malayalam"),
            new WhisperLanguage("Maltese"),
            new WhisperLanguage("Maori"),
            new WhisperLanguage("Marathi"),
            new WhisperLanguage("Moldavian"),
            new WhisperLanguage("Moldovan"),
            new WhisperLanguage("Mongolian"),
            new WhisperLanguage("Myanmar"),
            new WhisperLanguage("Nepali"),
            new WhisperLanguage("Norwegian"),
            new WhisperLanguage("Nynorsk"),
            new WhisperLanguage("Occitan"),
            new WhisperLanguage("Panjabi"),
            new WhisperLanguage("Pashto"),
            new WhisperLanguage("Persian"),
            new WhisperLanguage("Polish"),
            new WhisperLanguage("Portuguese"),
            new WhisperLanguage("Punjabi"),
            new WhisperLanguage("Pushto"),
            new WhisperLanguage("Romanian"),
            new WhisperLanguage("Russian"),
            new WhisperLanguage("Sanskrit"),
            new WhisperLanguage("Serbian"),
            new WhisperLanguage("Shona"),
            new WhisperLanguage("Sindhi"),
            new WhisperLanguage("Sinhala"),
            new WhisperLanguage("Sinhalese"),
            new WhisperLanguage("Slovak"),
            new WhisperLanguage("Slovenian"),
            new WhisperLanguage("Somali"),
            new WhisperLanguage("Spanish"),
            new WhisperLanguage("Sundanese"),
            new WhisperLanguage("Swahili"),
            new WhisperLanguage("Swedish"),
            new WhisperLanguage("Tagalog"),
            new WhisperLanguage("Tajik"),
            new WhisperLanguage("Tamil"),
            new WhisperLanguage("Tatar"),
            new WhisperLanguage("Telugu"),
            new WhisperLanguage("Thai"),
            new WhisperLanguage("Tibetan"),
            new WhisperLanguage("Turkish"),
            new WhisperLanguage("Turkmen"),
            new WhisperLanguage("Ukrainian"),
            new WhisperLanguage("Urdu"),
            new WhisperLanguage("Uzbek"),
            new WhisperLanguage("Valencian"),
            new WhisperLanguage("Vietnamese"),
            new WhisperLanguage("Welsh"),
            new WhisperLanguage("Yiddish"),
            new WhisperLanguage("Yoruba"),
        };
    }
}